// Generated by CoffeeScript 1.6.3
var _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Dashing.Tweets = (function(_super) {
  __extends(Tweets, _super);

  function Tweets() {
    this.nextTweet = __bind(this.nextTweet, this);
    _ref = Tweets.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Tweets.accessor('quote', function() {
    var _ref1;
    return "“" + ((_ref1 = this.get('current_tweet')) != null ? _ref1.body : void 0) + "”";
  });

  Tweets.prototype.ready = function() {
    this.currentIndex = 0;
    this.tweetElem = $(this.node).find('.tweet-container');
    this.nextTweet();
    return this.startCarousel();
  };

  Tweets.prototype.onData = function(data) {
    return this.currentIndex = 0;
  };

  Tweets.prototype.startCarousel = function() {
    return setInterval(this.nextTweet, 8000);
  };

  Tweets.prototype.nextTweet = function() {
    var tweets,
      _this = this;
    tweets = this.get('tweets');
    if (tweets) {
      return this.tweetElem.fadeOut(function() {
        _this.currentIndex = (_this.currentIndex + 1) % tweets.length;
        _this.set('current_tweet', tweets[_this.currentIndex]);
        return _this.tweetElem.fadeIn();
      });
    }
  };

  return Tweets;

})(Dashing.Widget);
